[preface]
[[story]]
=== The Story Behind BeagleConnect™ 

There are many stories behind BeagleConnect™, mine is just one of them. It begins
with my mom teaching me about computers. She told me I could anything I wanted
with ours, as long as I didn't open the case. This was the late-70s/early-80s, so
all she needed to do was put her https://en.wikipedia.org/wiki/Floppy_disk[floppy disk]
away and there wasn't risk of me damaging the family photo album or her ability to
do her work the next day. I listened and learned from her the basics of programming, but
it wasn't long before I wanted to take the computer apart. 

Initially exploring http://www.forrestmims.org/[Getting Started in Electronics] satisfied my
itch for quite a while. Eventually, I got a Commodore 64 and began connecting voice
synthesizer ICs to it. My interest in computers and electronics flourished into
an electrical engineering degree and a long career in the semiconductor industry.

Over this time, I've become more and more alarmed with the progress of technology. Now,
to be clear, I love technology. I love innovation and invention. It is just that some
things have evolved in a sort of tunnel-vision, without bringing everyone along.

But, what about keyboard users? As graphical user interfaces and mice took over computers, they rapidly became almost
unusable by my mom. She typed well, but the dexterity to move a mouse aluded her.
To satisfy the need to interact with locations on the screen, she adopted using a
joystick and her productivity came to a crawl. How is it that such assumptions could
be made impacting *all* computer users without any thoughtful provisions for what
already worked?